### ISSUE TITLE
CheckpointManager randomly crashes the kernel of the JupyterLab

### ISSUE THREAD

**Issue by vfdev-5** [google/orbax#1408]
The following code in multiple cells in the JupyterLab crashes randomly when executed:
```python
import jax
import flax
from flax import nnx
import orbax.checkpoint as ocp

print(jax.__version__)
print(flax.__version__)
print(ocp.__version__)

path = ocp.test_utils.erase_and_create_empty("/tmp/repro-crash-model/")
options = ocp.CheckpointManagerOptions(max_to_keep=2)
mngr = ocp.CheckpointManager(path, options=options)


def save_model(epoch):
    state = nnx.state(model)
    # We should convert PRNGKeyArray to the old format for Dropout layers
    # https://github.com/google/flax/issues/4231
    def get_key_data(x):
        if isinstance(x, jax._src.prng.PRNGKeyArray):
            if isinstance(x.dtype, jax._src.prng.KeyTy):
                return jax.random.key_data(x)
        return x

    serializable_state = jax.tree.map(get_key_data, state)
    mngr.save(epoch, args=ocp.args.StandardSave(serializable_state))
    mngr.wait_until_finished()

class TestModel(nnx.Module):
    def __init__(self, n1, n2, n3, *, rngs = nnx.Rngs(0)):
        self.m1 = nnx.Linear(n1, n2, rngs=rngs)
        self.dropout = nnx.Dropout(0.1, rngs=rngs)
        self.m1 = nnx.Linear(n2, n3, rngs=rngs)

    def __call__(self, x):
        x = self.m1(x)
        x = self.dropout(x)
        x = self.m2(x)
        return x
```

Here is the ipynb to reproduce the crash: https://gist.github.com/vfdev-5/da7f01b9c0c2948046b227a32db2cb2b

![Image](https://github.com/user-attachments/assets/bc933aff-ac0e-4e74-a641-032bc077e4cb)

**Comment by vfdev-5** [comment]
Env info:
- docker container: pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel, 
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

<details>
<summary>pip list</summary>

```

Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
aiohappyeyeballs             2.4.3
aiohttp                      3.10.10
aiosignal                    1.3.1
albucore                     0.0.20
albumentations               1.4.21
anaconda-anon-usage          0.4.4
annotated-types              0.7.0
anyio                        4.6.2.post1
archspec                     0.2.3
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
array_record                 0.5.1
arrow                        1.3.0
asttokens                    2.0.5
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.1.0
babel                        2.16.0
beautifulsoup4               4.12.3
bleach                       6.1.0
boltons                      23.0.0
Brotli                       1.0.9
cachetools                   5.5.0
certifi                      2024.7.4
cffi                         1.16.0
cfgv                         3.4.0
chardet                      4.0.0
charset-normalizer           2.0.4
chex                         0.1.87
click                        8.1.7
cloudpickle                  3.1.0
comm                         0.2.2
conda                        24.5.0
conda-build                  24.5.1
conda-content-trust          0.2.0
conda_index                  0.5.0
conda-libmamba-solver        24.1.0
conda-package-handling       2.3.0
conda_package_streaming      0.10.0
contourpy                    1.3.0
cryptography                 42.0.5
cycler                       0.12.1
datasets                     3.1.0
debugpy                      1.8.7
decorator                    5.1.1
defusedxml                   0.7.1
dill                         0.3.8
distlib                      0.3.9
distro                       1.9.0
dm-tree                      0.1.8
dnspython                    2.6.1
docstring_parser             0.16
einops                       0.8.0
etils                        1.9.4
eval_type_backport           0.2.0
executing                    0.8.3
expecttest                   0.2.1
fastjsonschema               2.20.0
filelock                     3.13.1
flatbuffers                  24.3.25
flax                         0.10.1
fonttools                    4.54.1
fqdn                         1.5.1
frozendict                   2.4.2
frozenlist                   1.5.0
fsspec                       2024.9.0
gast                         0.6.0
gcsfs                        2024.10.0
gmpy2                        2.1.2
google-api-core              2.22.0
google-auth                  2.35.0
google-auth-oauthlib         1.2.1
google-cloud-core            2.4.1
google-cloud-storage         2.18.2
google-crc32c                1.6.0
google-pasta                 0.2.0
google-resumable-media       2.7.2
googleapis-common-protos     1.65.0
grain                        0.2.2
grpcio                       1.67.1
h11                          0.14.0
h5py                         3.12.1
httpcore                     1.0.6
httpx                        0.27.2
huggingface-hub              0.26.2
humanize                     4.11.0
hypothesis                   6.108.4
identify                     2.6.1
idna                         3.7
immutabledict                4.2.0
importlib_resources          6.4.5
ipykernel                    6.29.5
ipython                      8.25.0
ipywidgets                   8.1.5
isoduration                  20.11.0
jax                          0.4.34
jax-cuda12-pjrt              0.4.34
jax-cuda12-plugin            0.4.34
jaxlib                       0.4.34
jaxtyping                    0.2.34
jedi                         0.19.1
Jinja2                       3.1.4
json5                        0.9.25
jsonpatch                    1.33
jsonpointer                  2.1
jsonschema                   4.19.2
jsonschema-specifications    2023.7.1
jupyter_client               8.6.3
jupyter_core                 5.7.2
jupyter-events               0.10.0
jupyter-lsp                  2.2.5
jupyter_server               2.14.2
jupyter_server_terminals     0.5.3
jupyterlab                   4.2.5
jupyterlab_pygments          0.3.0
jupyterlab_server            2.27.3
jupyterlab_widgets           3.0.13
jupytext                     1.16.4
keras                        3.6.0
keras-nightly                3.7.0.dev2024110103
kiwisolver                   1.4.7
libarchive-c                 2.9
libclang                     18.1.1
libmambapy                   1.5.8
lintrunner                   0.12.5
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   2.1.3
matplotlib                   3.9.2
matplotlib-inline            0.1.6
mdit-py-plugins              0.4.2
mdurl                        0.1.2
menuinst                     2.1.1
mistune                      3.0.2
mkl-fft                      1.3.8
mkl-random                   1.2.4
mkl-service                  2.4.0
ml-dtypes                    0.4.1
monai                        1.4.0
more-itertools               10.1.0
mpmath                       1.3.0
msgpack                      1.1.0
multidict                    6.1.0
multiprocess                 0.70.16
namex                        0.0.8
nbclient                     0.10.0
nbconvert                    7.16.4
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.3
ninja                        1.11.1.1
nodeenv                      1.9.1
notebook_shim                0.2.4
numpy                        1.26.4
nvidia-cublas-cu12           12.4.5.8
nvidia-cuda-cupti-cu12       12.4.127
nvidia-cuda-nvcc-cu12        12.6.77
nvidia-cuda-nvrtc-cu12       12.4.127
nvidia-cuda-runtime-cu12     12.4.127
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu12            11.2.1.3
nvidia-curand-cu12           10.3.5.147
nvidia-cusolver-cu12         11.6.1.9
nvidia-cusparse-cu12         12.3.1.170
nvidia-nccl-cu12             2.21.5
nvidia-nvjitlink-cu12        12.4.127
nvidia-nvtx-cu12             12.4.127
oauthlib                     3.2.2
opencv-python-headless       4.10.0.84
opt_einsum                   3.4.0
optax                        0.2.4
optree                       0.12.1
orbax-checkpoint             0.9.1
overrides                    7.7.0
packaging                    24.1
pandas                       2.2.3
pandocfilters                1.5.1
parso                        0.8.3
pexpect                      4.8.0
pillow                       11.0.0
pip                          24.0
pkginfo                      1.10.0
platformdirs                 3.10.0
pluggy                       1.0.0
pre_commit                   4.0.1
prometheus_client            0.21.0
promise                      2.3
prompt-toolkit               3.0.43
propcache                    0.2.0
proto-plus                   1.25.0
protobuf                     5.28.2
psutil                       5.9.0
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyarrow                      18.0.0
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pycosat                      0.6.6
pycparser                    2.21
pydantic                     2.9.2
pydantic_core                2.23.4
Pygments                     2.15.1
pyparsing                    3.2.0
PySocks                      1.7.1
python-dateutil              2.9.0.post0
python-etcd                  0.4.5
python-json-logger           2.0.7
pytz                         2024.1
PyYAML                       6.0.1
pyzmq                        26.2.0
referencing                  0.30.2
regex                        2024.11.6
requests                     2.32.3
requests-oauthlib            2.0.0
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.9.2
rpds-py                      0.10.6
rsa                          4.9
ruamel.yaml                  0.17.21
safetensors                  0.4.5
scipy                        1.14.1
seaborn                      0.13.2
Send2Trash                   1.8.3
setuptools                   69.5.1
simple-parsing               0.1.6
simsimd                      6.0.1
six                          1.16.0
sniffio                      1.3.1
sortedcontainers             2.4.0
soupsieve                    2.5
stack-data                   0.2.0
stringzilla                  3.10.8
sympy                        1.13.1
tb-nightly                   2.19.0a20241106
tensorboard                  2.18.0
tensorboard-data-server      0.7.2
tensorflow                   2.18.0
tensorflow-datasets          4.9.7
tensorflow-io-gcs-filesystem 0.37.1
tensorflow-metadata          1.16.1
tensorstore                  0.1.66
termcolor                    2.5.0
terminado                    0.18.1
tiktoken                     0.8.0
tinycss2                     1.3.0
tokenizers                   0.20.3
toml                         0.10.2
toolz                        1.0.0
torch                        2.5.1
torchaudio                   2.4.0
torchelastic                 0.2.2
torchvision                  0.20.1
tornado                      6.4.1
tqdm                         4.66.4
traitlets                    5.14.3
transformers                 4.46.3
treescope                    0.1.5
triton                       3.1.0
truststore                   0.8.0
typeguard                    2.13.3
types-dataclasses            0.6.6
types-python-dateutil        2.9.0.20241003
typing_extensions            4.11.0
tzdata                       2024.2
uri-template                 1.3.0
urllib3                      2.2.2
virtualenv                   20.26.6
wcwidth                      0.2.5
webcolors                    24.8.0
webencodings                 0.5.1
websocket-client             1.8.0
Werkzeug                     3.1.2
wheel                        0.43.0
widgetsnbextension           4.0.13
wrapt                        1.16.0
xxhash                       3.5.0
yarl                         1.17.1
zipp                         3.20.2
zstandard                    0.22.0
```

</details>

JupyterLab console shows the following before the crash:
```
Traceback (most recent call last):                                                                                                                                                                                                 
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                                                          
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                                                                     
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>                                                                                                                                       
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1921, in _run_once
    handle = self._ready.popleft()
             ^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from an empty deque
```

Hope this helps

**Comment by niketkumar** [comment]
> repro code in the single cell does not crash (at least I've never seen)

Just to be clear, here by `cell` you meant the notebook cell. Correct?

**Comment by vfdev-5** [comment]
> > repro code in the single cell does not crash (at least I've never seen)
> 
> Just to be clear, here by `cell` you meant the notebook cell. Correct?

Yes, if I merge all notebook code cells into a single cell, I can't repro the crash.
When the code is distributed into multiple cells as in the ipynb, than I can get notebook kernel crash rather frequently.

**Comment by rajasekharporeddy** [comment]
Hi @vfdev-5 

I could not reproduce the issue when I tested it on JupyterLab locally on MAC OS and on Colab CPU with Orbax-Checkpoint 0.11.0, JAX 0.5.0 and Flax 0.10.2. Please find the attached screenshot of JupyterLab for reference.

![Image](https://github.com/user-attachments/assets/ea370f0f-0102-40f2-9e0a-c93002d648d4)

Could please verify if issue still persists in your setup?

Thank you.

**Comment by vfdev-5** [comment]
Hi @rajasekharporeddy , I retried on my setup and on few others and yes I could repro the crash. Here are detailed repro steps on linux machine with docker:

1) Run docker container using python:3.13-slim-bookworm image:
```bash
docker run -it --rm --name=jax-ai-test -v $PWD:/ws -w /ws --ipc=host --network=host python:3.13-slim-bookworm /bin/bash
```

2) Install dependencies in the container:
```bash
pip install jupyterlab
pip install jax[cpu] flax orbax
```

3) Start jupyterlab and open it in the browser
```
jupyter lab --port 8844 --allow-root --no-browser 
```

4) Run the following multiple times: restart jupyter kernel and execute cells. On the 2nd, 3rd tries it crashes with 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
    ~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2018, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
[I 2025-01-29 08:47:59.223 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2025-01-29 08:47:59.223 ServerApp] kernel cb35e8f3-f9f9-42e5-8da9-139047ef2e73 restarted
```

**Comment by vfdev-5** [comment]
Asking around, I was suggested to try using the alpha version of ipykernel which has a substantial rewrite: `pip install -U --pre 'ipykernel>=v7.0.0a0'`

Using that I can't reproduce the crash. I think we can close the issue in orbax as mostly unrelated to orbax code.

**Comment by burnpanck** [comment]
Same issue here, observe with `orbax-checkpoint 0.11.9` and both `ipykernel 6.30.0` as-well as `ipykernel 7.0.0.a1`. With the former, I get the same traceback as @vfdev-5 : 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
    ~~~~~~~~~^^
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "/Users/yves/.pyenv/versions/3.13.2/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2025, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```
With `ipykernel 7.0.0a1`, I don't see any traceback on the Jupyter console, though it still crashes the kernel. The crash is definitely related to orbax - commenting out just the orbax stuff makes it go away.

I do have to say, the fact that I see `asyncio` in that traceback worries me a lot, and makes me questioning the design of orbax: Do you somehow mess with the `asyncio` event loop of Jupyter, despite no `async` visible on any API? That would be a big red flag for me.

**Comment by cpgaffney1** [comment]
`asyncio` is used *a lot* under the hood, but the final layer the user sees wraps everything in a future-like interface. We use `nest_asyncio` to allow it to run on colabs and Jupyter notebooks - this may be the likeliest spot to look for a culprit.

**Comment by burnpanck** [comment]
Hm. In this case, I would have preferred an clean, structured async API instead. There is a reason why event loops don't like to be nested. On the other hand, with structured concurrency, things like `wait_until_finished` wouldn't be needed (nor would they be allowed: structured concurrency forbids implicit lifetimes of async tasks). That's a real bummer that there is no way to use orbax without it stomping over the main event loop.

**Comment by burnpanck** [comment]
I just noticed that `etils.epath.Path` accessing a file on GCS crashes my notebook (with nothing else in there). The crash was fixable by setting `ETILS_USE_TF=false` in the environment, i.e. disabling their default choice of using a TF backend when they see TF is installed. Could this be related to this bug here?
