### ISSUE TITLE
`No module named 'orbax.checkpoint._src.path'` when used as bazel pip dependency

### ISSUE THREAD

**Issue by hartikainen** [google/orbax#1429]
I'm trying to use `orbax-checkpoint` as a transitive pip dependency of [`brax`](https://github.com/google/brax/) within my bazel setup. I've declared `brax`, and thus also `orbax-checkpoint`, as a dependency via pip/pypi. When running any of my bazel targets that depend on the pip-installed `orbax-checkpoint`, I get `No module named 'orbax.checkpoint._src.path'`.

I created a minimal reproduction here: https://github.com/google/orbax/compare/main...hartikainen:orbax:bazel-pip-dependency-error. And here's the error I get running it:
```bash
$ cd ./pypi_dependency_test
$ bazel run //:pypi_dependency_test                                  2.336s
INFO: Analyzed target //:pypi_dependency_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:pypi_dependency_test up-to-date:
  bazel-bin/pypi_dependency_test
INFO: Elapsed time: 0.147s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh ./pypi_dependency_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:pypi_dependency_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel/aae0c90911bf9b49b7fec6ebc38b486f/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/pypi_dependency_test.runfiles/_main/pypi_dependency_test.py", line 3, in <module>
    import orbax.checkpoint
  File "/private/var/tmp/_bazel/aae0c90911bf9b49b7fec6ebc38b486f/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/pypi_dependency_test.runfiles/rules_python~~pip~pypi_312_orbax_checkpoint/site-packages/orbax/checkpoint/__init__.py", line 23, in <module>
    from orbax.checkpoint import aggregate_handlers
  File "/private/var/tmp/_bazel/aae0c90911bf9b49b7fec6ebc38b486f/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/pypi_dependency_test.runfiles/rules_python~~pip~pypi_312_orbax_checkpoint/site-packages/orbax/checkpoint/aggregate_handlers.py", line 25, in <module>
    from orbax.checkpoint import utils
  File "/private/var/tmp/_bazel/aae0c90911bf9b49b7fec6ebc38b486f/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/pypi_dependency_test.runfiles/rules_python~~pip~pypi_312_orbax_checkpoint/site-packages/orbax/checkpoint/utils.py", line 30, in <module>
    from orbax.checkpoint._src.path import async_utils
ModuleNotFoundError: No module named 'orbax.checkpoint._src.path'
```

Does anyone have an idea what might be causing this? I can't reproduce this with other pip systems like vanilla venv or even when creating the venv with [`rules_uv`](https://github.com/theoremlp/rules_uv?tab=readme-ov-file#create_venv) and running python manually through it.

**Comment by hartikainen** [comment]
I managed to solve the most immediate issue by removing the `BUILD` files from the wheel using Bazel patches as shown here: https://github.com/google/orbax/compare/main...hartikainen:orbax:bazel-pip-dependency-error. I guess the `BUILD` files somehow trip `rules_python`.

Is it intentional that only the following two folders have `BUILD`-files in them?
- https://github.com/google/orbax/blob/main/checkpoint/orbax/checkpoint/_src/path/BUILD
- https://github.com/google/orbax/blob/main/checkpoint/orbax/checkpoint/_src/path/snapshot/BUILD

Should they be excluded from the wheels? Are they supposed to exist in the repository at all?

**Comment by hartikainen** [comment]
I managed fix the `tensorstore` issue by explictly depending on `tensorstore==0.1.69`. The [diff between `tensorstore==0.1.69` and `tensorstore==0.1.71`](https://github.com/google/tensorstore/compare/v0.1.69...v0.1.71) is quite large and I don't know exactly what's gone wrong there.

**Comment by cpgaffney1** [comment]
There are only two BUILD files because we are in the process of adding more for testing purposes. Probably we could just exclude these from the package published to PyPI since they aren't really necessary for users.

**Comment by hartikainen** [comment]
Excluding the BUILD files from the wheel would be awesome. That would fix the issue.

**Comment by hartikainen** [comment]
I'm still facing this issue. @cpgaffney1, does #1458 look like it could be merged?

**Comment by jimmyt857** [comment]
We are affected by this issue as well (we use `orbax-checkpoint==0.11.3`, but it affects all versions `>=0.10.2`). Would really appreciate if #1458 could be merged!

**Comment by jimmyt857** [comment]
So sorry to bother you all, I know you must be very busy. Will there be time to address this bug soon, or is there an estimate of when it might happen? This project is currently unusable for all users building with Bazel.

**Comment by cpgaffney1** [comment]
Hi @liangyaning33 could you take a look at adding this exclusion? Thanks!
