### ISSUE TITLE
Incompatibility with Haiku

### ISSUE THREAD

**Issue by chriscarmona** [google/orbax#339]
I am trying to use Orbax for checkpointing a model in [Haiku](https://github.com/deepmind/dm-haiku), but it's been quite problematic.

The problem seems to be that Orbax struggles with keys containing the `/` character. Haiku uses `/` for managing parameters in nested modules, such as a simple MLP network.

Here is a minimal example replicating the problem:

```python
import pathlib
from jax import numpy as jnp
import orbax
import orbax.checkpoint
import haiku as hk

@hk.transform
def forward_fn(inputs):
  # net = hk.Linear(output_size=2) # This works
  net = hk.nets.MLP(output_sizes=[2, 2], activate_final=True)  # This doesn't work
  return net(inputs)

prng_seq = hk.PRNGSequence(0)
params = forward_fn.init(next(prng_seq), jnp.ones((1, 5)))

ckpt_dir = str(pathlib.Path.home() / 'foo')
orbax_mngr = orbax.checkpoint.CheckpointManager(
    ckpt_dir,
    {'state': orbax.checkpoint.PyTreeCheckpointer()},
    options=orbax.checkpoint.CheckpointManagerOptions(max_to_keep=1),
)
orbax_mngr.save(step=0, items={'state': params})
```

For the MLP network, params is a tree with the first level keys `['mlp/~/linear_0', 'mlp/~/linear_1']`, which creates a problem when I try to save it using the checkpoint manager.

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/foo/0.orbax-checkpoint-tmp-1685818375792355/state.orbax-checkpoint-tmp-1685818375868924/mlp/~/linear_0.w'
```

**Comment by cpgaffney1** [comment]
A similar issue has been reported before here: https://github.com/google/orbax/issues/304.

I'm afraid right now you would just have to change the names before saving. I can look into a more robust solution, but might be a little while before I get to it. I'll leave this issue open in the meantime.

**Comment by cpgaffney1** [comment]
This should be supported in the latest release. Feel free to reopen if you have an issue with the new solution.

**Comment by chriscarmona** [comment]
Many thanks for the prompt response! I verified that new release solves the problem

**Comment by chriscarmona** [comment]
Hi again, I recently upgraded orbax to the latest version and found that there's is again an issue for orbax handling trees with the `~` character, as used by Haiku. The error now is as follows:
```
Traceback (most recent call last):
  File "/workspaces/modularbayes/examples/bar.py", line 23, in <module>
    orbax_mngr.save(step=0, items={'state': params})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/checkpoint_manager.py", line 496, in save
    self._checkpointers[k].save(item_dir, item, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/checkpointer.py", line 79, in save
    self._handler.save(tmpdir, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 818, in save
    asyncio.run(async_save(directory, item, *args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 811, in async_save
    commit_futures = await self.async_save(*args, **kwargs)  # pytype: disable=bad-return-type
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 786, in async_save
    commit_futures = await asyncio.gather(*serialize_ops)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/orbax/checkpoint/type_handlers.py", line 893, in serialize
    open_future = ts.open(
ValueError: Error parsing object member "json_pointer": JSON Pointer requires '~' to be followed by '0' or '1': "/mlp/~/linear_0.b" [source locations='tensorstore/internal/json_binding/json_binding.h:861\ntensorstore/internal/json_binding/json_binding.h:825']
sys:1: RuntimeWarning: coroutine 'async_serialize' was never awaited
```
I will open a new issue
