### ISSUE TITLE
error saving state

### ISSUE THREAD

**Issue by jakubMitura14** [google/orbax#448]
Hello I get error as below while trying to save state in pmapped model
```
Error parsing object member "base": Error parsing object member "metadata": Error parsing object member "chunks": Array has length 0 but should have length 1
```
code is pretty basic 
```
        orbax_checkpointer = orbax.checkpoint.PyTreeCheckpointer()
        ckpt = {'state': state} #, 'config': cfg  ,'loss':loss
        save_args = orbax_utils.save_args_from_target(ckpt)
        orbax_checkpointer.save(chechpoint_epoch_folder, ckpt, save_args=save_args)
```
versions
```
Python 3.10.12
orbax-checkpoint             0.2.3
jax                          0.4.10
flax                         0.7.0
```
Generally code is run inside official jax nvidia container 

nvcr.io/nvdlfwea/jax/jax:23.05-py3
model is distributed but not sharded over 2 gpus

full error

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/Jax_cuda_med/j_med/ztest_geometric/run_geometric_sv.py", line 341, in <module>
    main_train(cfg)
  File "/workspaces/Jax_cuda_med/j_med/ztest_geometric/run_geometric_sv.py", line 317, in main_train
    state,loss=train_epoch(batch_images[index,:,:,:,:,:],batch_labels[index,:,:,:,:,:],batch_images_prim,curr_label,epoch,index
  File "/workspaces/Jax_cuda_med/j_med/ztest_geometric/run_geometric_sv.py", line 241, in train_epoch
    save_checkpoint(index,epoch,cfg,checkPoint_folder,state,np.mean(epoch_loss))
  File "/workspaces/Jax_cuda_med/j_med/ztest_geometric/data_utils.py", line 76, in save_checkpoint
    orbax_checkpointer.save(chechpoint_epoch_folder, ckpt, save_args=save_args)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/checkpointer.py", line 77, in save
    self._handler.save(tmpdir, item, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 421, in save
    asyncio.run(async_save(directory, item, *args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 414, in async_save
    commit_futures = await self.async_save(*args, **kwargs)  # pytype: disable=bad-return-type
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 394, in async_save
    commit_futures = await asyncio.gather(*copy_futures)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 386, in serialize
    return await handler.serialize(value, info, args)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/type_handlers.py", line 502, in serialize
    await serialization.async_serialize(
  File "/usr/local/lib/python3.10/dist-packages/jax/experimental/array_serialization/serialization.py", line 153, in async_serialize
    ts.Spec(tensorstore_spec),
ValueError: Error parsing object member "base": Error parsing object member "metadata": Error parsing object member "chunks": Array has length 0 but should have length 1 [source locations='tensorstore/internal/json_binding/json_binding.h:859,tensorstore/internal/json_binding/json_binding.h:859,tensorstore/internal/json_binding/json_binding.h:859']
```
Thanks for any clue how to resolve it

**Comment by cpgaffney1** [comment]
Be cautious when using pmap - Orbax only supports pmap output arrays that are fully replicated. If the array is in host memory, that is fine too. If you have a pmap array that has different shards on different devices, you'll need to switch to pjit.

**Comment by jakubMitura14** [comment]
Hello I just pmap over batch dimension of the data do not shard parameters and invoke orbax outside the pmapped function

Should I use unreplicate on state before saving to orbax?

**Comment by cpgaffney1** [comment]
Notice the `save_args_from_target`, from Flax, which constructs arguments where `aggregate=False` if the array is a multi-device array, meaning that it is not fully replicated. Since the stack trace indicates that it is using the TypeHandler code path, I believe that some of your arrays are not fully replicated. If you identify the arrays in question, you'll need to need to ensure these are fully replicated.

Alternatively, if you use pjit, `aggregate=False` should just work for these parameters.

**Comment by jakubMitura14** [comment]
Thanks @cpgaffney1 it was it !
